spring:
  application:
    name: ad-search-client
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false # 控制在懒加载的时候, 如果应用程序中对一些bean 执行过懒加载, 如果为true可能会对找不到一些Bean的配置而出现错误
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    hikari:
      password: 1212wasd
      username: root
      maximum-pool-size: 10
      connection-timeout: 30000
      minimum-idle: 3
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ad_service?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 5
        max-wait: 600
    timeout: 6000
#    password: 1212wasd
#      shutdown-timeout: 1000ms
server:
  port: 8003
  servlet:
    context-path: /ad-search

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

feign:
  hystrix:
    enabled: true

# 暴露所有监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

adconf:
  mysql:
    host: 127.0.0.1
    port: 3307
    username: root
    password: 1212wasd
    binlogName:
    position: -1